#
# Live LiDAR Point Cloud Visualizer for iRobot Create3
# ====================================================
#
# Real-time visualization of the LiDAR point cloud generated by the
# GENERATE_COORDS task.
#
# Features:
#   • Live updating point cloud (refreshes every 50 ms)
#   • Robot front (positive X) points UP on screen
#   • Robot shown as a green triangle with accurate heading
#   • Clean dark theme matching PIDTuner and ControllerVisualizer
#
# Created by Scottcandy34
#

import math
import tkinter as tk
from typing import Callable, List, Tuple, TYPE_CHECKING

if TYPE_CHECKING:
    from create3 import RobotNode


class PointCloudVisualizer:
    """Real-time LiDAR point cloud visualizer with robot pose overlay.

    Displays the world-frame point cloud from the GENERATE_COORDS task.
    Robot front (positive X) points upward on screen. Updates every 50 ms.
    """

    def __init__(self, get_point_cloud: Callable[[], List[Tuple[float, float]] | None], robot: "RobotNode") -> None:
        """Launch the live point cloud visualizer.

        Parameters
        ----------
        get_point_cloud : callable
            Function that returns the latest point cloud (list of (x, y) tuples).
            Example: `lambda: task_scheduler.get_task_output(Tasks.GENERATE_COORDS)`
        robot : RobotNode
            Robot node providing current position and heading.
        """
        self.get_point_cloud = get_point_cloud
        self.robot = robot

        self.root = tk.Tk()
        self.root.title("iRobot Create3 - Live Point Cloud")
        self.root.configure(bg="#0a0a0a")
        self.root.resizable(False, False)

        # Canvas (800x800 for good resolution)
        self.canvas = tk.Canvas(
            self.root,
            width=800,
            height=800,
            bg="#111111",
            highlightthickness=0,
        )
        self.canvas.pack(padx=20, pady=20)

        # Store canvas items for efficient redrawing
        self.point_items: list[int] = []
        self.robot_item: int | None = None
        self.pose_text: int | None = None

        # Start real-time update loop
        self._update()

        self.root.protocol("WM_DELETE_WINDOW", self._on_close)
        self.root.mainloop()

    def _update(self) -> None:
        """Fetch latest point cloud and robot pose, redraw everything."""
        coords = self.get_point_cloud()
        pose = self.robot.get_position()

        # Clear previous frame
        for item in self.point_items:
            self.canvas.delete(item)
        self.point_items.clear()

        if self.robot_item is not None:
            self.canvas.delete(self.robot_item)
        if self.pose_text is not None:
            self.canvas.delete(self.pose_text)

        if coords:
            # Draw point cloud
            cx, cy = 400, 400          # canvas center
            scale = 3.0                # pixels per cm

            for p in coords:
                if p is None:
                    continue
                px, py = p

                # Translate relative to robot
                dx = px - pose.x
                dy = py - pose.y

                # Rotate so robot heading points UP (positive X = up)
                angle_rad = math.radians(-pose.angle)
                rx = dx * math.cos(angle_rad) - dy * math.sin(angle_rad)
                ry = dx * math.sin(angle_rad) + dy * math.cos(angle_rad)

                # Map to canvas coordinates (X forward = up, Y left = right)
                screen_x = cx - ry * scale
                screen_y = cy - rx * scale

                item = self.canvas.create_oval(
                    screen_x - 2, screen_y - 2,
                    screen_x + 2, screen_y + 2,
                    fill="#00ff88", outline=""
                )
                self.point_items.append(item)

            # Draw robot as green triangle (pointing up = forward)
            self.robot_item = self.canvas.create_polygon(
                cx,      cy - 25,   # nose (forward)
                cx - 18, cy + 18,   # left rear
                cx + 18, cy + 18,   # right rear
                fill="#00cc66", outline="#ffffff", width=3
            )

            # Show current pose
            self.pose_text = self.canvas.create_text(
                20, 30,
                text=f"Pose: {pose.x:.1f}, {pose.y:.1f}, {pose.angle:.1f}°",
                fill="#aaaaaa", anchor="nw", font=("Consolas", 10)
            )

        # Schedule next update
        self.root.after(50, self._update)

    def _on_close(self) -> None:
        """Cleanly close the visualizer."""
        self.root.destroy()