from .controller import controller_task
from .generate_coords import generate_coords_task
from .history_keeper import history_keeper_task
from .ir_lightring import ir_lightring_task
from .lidar_lightring import lidar_lightring_task
from .simple_wall_follower import simple_wall_follower_task
from .wall_detection import wall_detection_task
from .generate_point_cloud import generate_point_cloud_task