#
# Live LiDAR Coordinate Points Visualizer for iRobot Create3
# ========================================================
#
# This example visualizes the raw coordinate points generated by the
# GENERATE_COORDS task in real time.
#
# Features:
#   • Live updating point cloud (refreshes every 50 ms)
#   • Robot front (positive X) points UP on screen
#   • Robot shown as a green triangle with accurate heading
#   • Clean dark theme matching PIDTuner and ControllerVisualizer
#
# Created by Scottcandy34
#

import sys
from pathlib import Path

# =============================================================================
# Make the example runnable from both examples/ and the project root
# =============================================================================
script_dir = Path(__file__).parent.resolve()

if (script_dir / "create3").exists():
    # Running from project root
    sys.path.insert(0, str(script_dir))
elif (script_dir.parent / "create3").exists():
    # Running from inside examples/
    sys.path.insert(0, str(script_dir.parent))
# =============================================================================

from create3 import RobotNode, CompanionNode
from create3.utils.display import PointCloudVisualizer
from create3.models.common import Tasks

def main() -> None:
    """Run the live LiDAR coordinate points visualizer example."""

    # Initialize nodes
    robot = RobotNode(enable_scheduler=True)
    companion = CompanionNode(enable_scheduler=True)

    # Start the coordinate generation task
    robot.scheduler.add_task(Tasks.HISTORY_KEEPER)
    robot.scheduler.add_task(companion.tasks.GENERATE_COORDS)

    # Launch live point cloud visualizer
    PointCloudVisualizer(get_point_cloud=lambda: robot.scheduler.get_task_output(companion.tasks.GENERATE_COORDS), robot=robot)

    # Clean shutdown (reached when visualizer window is closed)
    robot.shutdown()
    companion.shutdown()

# =============================================================================
if __name__ == "__main__":
    main()